# SPDX-License-Identifier: GPL-3.0-or-later
"""Minimal stubs for ``gi.repository`` namespaces used by ready2rip.

These exist only for static analysis. Runtime still uses system PyGObject.
Nested classes are real types so annotations like ``list[Gtk.Widget]`` work.
"""

from collections.abc import Callable
from typing import Any, ClassVar

class _GI:
    """Stand-in for unlisted GI names (still usable in type expressions)."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    @classmethod
    def __class_getitem__(cls, item: Any) -> Any: ...

class GLib:
    class Error(Exception): ...
    SOURCE_REMOVE: ClassVar[bool]
    SOURCE_CONTINUE: ClassVar[bool]
    @staticmethod
    def idle_add(function: Callable[..., Any], *args: Any) -> int: ...
    @staticmethod
    def timeout_add(interval: int, function: Callable[..., Any], *args: Any) -> int: ...
    @staticmethod
    def set_application_name(name: str) -> None: ...
    @staticmethod
    def set_prgname(name: str) -> None: ...
    @staticmethod
    def Bytes(data: bytes | None = None) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

class Gio:
    class ApplicationFlags:
        DEFAULT_FLAGS: ClassVar[int]
        def __getattr__(self, name: str) -> Any: ...
    class SimpleAction:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        @staticmethod
        def new(name: str, parameter_type: Any = None) -> Gio.SimpleAction: ...
        def connect(self, signal: str, callback: Callable[..., Any]) -> Any: ...
        def __getattr__(self, name: str) -> Any: ...
    class Settings:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        @staticmethod
        def new(schema_id: str) -> Gio.Settings: ...
        @staticmethod
        def new_full(schema: Any, backend: Any, path: Any) -> Gio.Settings: ...
        @staticmethod
        def sync() -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class SettingsSchemaSource:
        @staticmethod
        def get_default() -> Any: ...
        def __getattr__(self, name: str) -> Any: ...
    class File:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        @staticmethod
        def new_for_path(path: str) -> Gio.File: ...
        def __getattr__(self, name: str) -> Any: ...
    class Cancellable:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

class Gtk:
    class Widget:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class CheckButton(Widget): ...
    class ToggleButton(Widget): ...
    class Button(Widget): ...
    class Entry(Widget): ...
    class Label(Widget): ...
    class Stack(Widget): ...
    class Image(Widget): ...
    class Picture(Widget): ...
    class ProgressBar(Widget): ...
    class Revealer(Widget): ...
    class Overlay(Widget): ...
    class Frame(Widget): ...
    class Window(Widget): ...
    class ApplicationWindow(Window): ...
    class Application:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class Adjustment:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class SizeGroup:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class SizeGroupMode:
        HORIZONTAL: ClassVar[int]
        VERTICAL: ClassVar[int]
        BOTH: ClassVar[int]
        NONE: ClassVar[int]
    class Align:
        FILL: ClassVar[int]
        START: ClassVar[int]
        END: ClassVar[int]
        CENTER: ClassVar[int]
        BASELINE: ClassVar[int]
    class ContentFit:
        FILL: ClassVar[int]
        CONTAIN: ClassVar[int]
        COVER: ClassVar[int]
        SCALE_DOWN: ClassVar[int]
    class License:
        GPL_3_0: ClassVar[int]
        def __getattr__(self, name: str) -> Any: ...
    class EventControllerMotion:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def connect(self, signal: str, callback: Callable[..., Any]) -> Any: ...
        def __getattr__(self, name: str) -> Any: ...
    class CssProvider:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class StyleContext:
        @staticmethod
        def add_provider_for_display(*args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class IconTheme:
        @staticmethod
        def get_for_display(display: Any) -> Gtk.IconTheme: ...
        def __getattr__(self, name: str) -> Any: ...
    class FileDialog:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class FileFilter:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class StringList:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class Template:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
        @staticmethod
        def Child() -> Any: ...
        @staticmethod
        def Callback() -> Callable[[Any], Any]: ...
        def __getattr__(self, name: str) -> Any: ...
    STYLE_PROVIDER_PRIORITY_APPLICATION: ClassVar[int]
    def __getattr__(self, name: str) -> _GI: ...

class Adw:
    class Application:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class ApplicationWindow(Gtk.ApplicationWindow): ...
    class Window(Gtk.Window): ...
    class Dialog:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class AboutDialog(Dialog): ...
    class AlertDialog(Dialog): ...
    class ActionRow(Gtk.Widget): ...
    class EntryRow(Gtk.Widget): ...
    class SwitchRow(Gtk.Widget): ...
    class SpinRow(Gtk.Widget): ...
    class ComboRow(Gtk.Widget): ...
    class PreferencesGroup(Gtk.Widget): ...
    class PreferencesPage(Gtk.Widget): ...
    class StatusPage(Gtk.Widget): ...
    class Toast:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class ToastOverlay(Gtk.Widget): ...
    class HeaderBar(Gtk.Widget): ...
    class ToolbarView(Gtk.Widget): ...
    class Breakpoint:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        @staticmethod
        def new(condition: Any) -> Adw.Breakpoint: ...
        def __getattr__(self, name: str) -> Any: ...
    class BreakpointCondition:
        @staticmethod
        def parse(text: str) -> Adw.BreakpointCondition: ...
        def __getattr__(self, name: str) -> Any: ...
    class BreakpointBin(Gtk.Widget): ...
    class OverlaySplitView(Gtk.Widget): ...
    class Banner(Gtk.Widget): ...
    class Clamp(Gtk.Widget): ...
    class StyleManager:
        @staticmethod
        def get_default() -> Adw.StyleManager: ...
        def __getattr__(self, name: str) -> Any: ...
    class ColorScheme:
        DEFAULT: ClassVar[int]
        FORCE_LIGHT: ClassVar[int]
        FORCE_DARK: ClassVar[int]
        PREFER_LIGHT: ClassVar[int]
        PREFER_DARK: ClassVar[int]
    def __getattr__(self, name: str) -> _GI: ...

class Gdk:
    class Texture:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        @staticmethod
        def new_from_bytes(bytes: Any) -> Gdk.Texture: ...
        def __getattr__(self, name: str) -> Any: ...
    class MemoryTexture(Texture): ...
    class Display:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class Paintable:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    def __getattr__(self, name: str) -> _GI: ...

class GdkPixbuf:
    class Pixbuf:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    class PixbufLoader:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    def __getattr__(self, name: str) -> _GI: ...

class Pango:
    class EllipsizeMode:
        NONE: ClassVar[int]
        START: ClassVar[int]
        MIDDLE: ClassVar[int]
        END: ClassVar[int]
    class AttrList:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def __getattr__(self, name: str) -> Any: ...
    def __getattr__(self, name: str) -> _GI: ...

def __getattr__(name: str) -> Any: ...
