# SPDX-License-Identifier: GPL-3.0-or-later
from typing import Any

from mutagen.id3 import ID3

class WAVE:
    tags: ID3 | None
    def __init__(self, filename: Any = None, *args: Any, **kwargs: Any) -> None: ...
    def add_tags(self) -> None: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
