# SPDX-License-Identifier: GPL-3.0-or-later
from collections.abc import Iterator, MutableMapping
from typing import Any

class OggOpus(MutableMapping[str, Any]):
    def __init__(self, filename: Any = None, *args: Any, **kwargs: Any) -> None: ...
    def save(self, filename: Any = None, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __getattr__(self, name: str) -> Any: ...
