# SPDX-License-Identifier: GPL-3.0-or-later
"""Minimal Pillow stubs for static analysis. Runtime uses the real package."""

from typing import Any

class Image:
    class Resampling:
        LANCZOS: int
        BILINEAR: int
        NEAREST: int
        BICUBIC: int
        BOX: int
        HAMMING: int

    mode: str
    size: tuple[int, int]
    def __enter__(self) -> Image: ...
    def __exit__(self, *args: Any) -> None: ...
    def convert(self, mode: str) -> Image: ...
    def split(self) -> tuple[Any, ...]: ...
    def paste(self, im: Image, mask: Any = None) -> None: ...
    def thumbnail(self, size: tuple[int, int], resample: int = ...) -> None: ...
    def save(self, fp: Any, format: str | None = None, **kwargs: Any) -> None: ...
    @staticmethod
    def open(fp: Any, mode: str = 'r') -> Image: ...
    @staticmethod
    def new(mode: str, size: tuple[int, int], color: Any = 0) -> Image: ...
    def __getattr__(self, name: str) -> Any: ...
