# SPDX-License-Identifier: GPL-3.0-or-later
from typing import Any

class Frame:
    encoding: int
    text: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class TIT2(Frame): ...
class TRCK(Frame): ...
class TALB(Frame): ...
class TPE1(Frame): ...
class TPE2(Frame): ...
class TPOS(Frame): ...
class TDRC(Frame): ...
class TDOR(Frame): ...
class TXXX(Frame):
    desc: str

class APIC(Frame):
    mime: str
    type: int
    desc: str
    data: bytes

class UFID(Frame):
    owner: str
    data: bytes

class ID3:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add(self, frame: Frame) -> None: ...
    def delall(self, key: str) -> None: ...
    def getall(self, key: str) -> list[Any]: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
